version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8787:8787"
    environment:
      - NODE_ENV=development
      - PORT=8787
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
